// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: order/order.proto

package order

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderServiceClient interface {
	CreateLocalOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*CreateResponse, error)
	CreateDeliveryOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*CreateResponse, error)
	GetOrdersByUser(ctx context.Context, in *OrdersByUserRequest, opts ...grpc.CallOption) (*OrdersResponse, error)
	GetOrdersByKitchen(ctx context.Context, in *RequestKitchen, opts ...grpc.CallOption) (*OrderProductsResponse, error)
	GetOrders(ctx context.Context, in *OrdersRequest, opts ...grpc.CallOption) (*OrdersResponse, error)
	GetOrdersByEstablishment(ctx context.Context, in *OrdersRequest, opts ...grpc.CallOption) (*OrdersResponse, error)
	GetOrderByWaiter(ctx context.Context, in *ID, opts ...grpc.CallOption) (*OrdersResponse, error)
	GetOrderPendingByWaiter(ctx context.Context, in *ID, opts ...grpc.CallOption) (*OrdersResponse, error)
	GetOrderByID(ctx context.Context, in *GetOrderByIDRequest, opts ...grpc.CallOption) (*OrderResponse, error)
	AddProductsToOrder(ctx context.Context, in *AddProductsToOrderRequest, opts ...grpc.CallOption) (*AddProductsToOrderResponse, error)
}

type orderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderServiceClient(cc grpc.ClientConnInterface) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) CreateLocalOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/proto.order.order.OrderService/CreateLocalOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) CreateDeliveryOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/proto.order.order.OrderService/CreateDeliveryOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetOrdersByUser(ctx context.Context, in *OrdersByUserRequest, opts ...grpc.CallOption) (*OrdersResponse, error) {
	out := new(OrdersResponse)
	err := c.cc.Invoke(ctx, "/proto.order.order.OrderService/GetOrdersByUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetOrdersByKitchen(ctx context.Context, in *RequestKitchen, opts ...grpc.CallOption) (*OrderProductsResponse, error) {
	out := new(OrderProductsResponse)
	err := c.cc.Invoke(ctx, "/proto.order.order.OrderService/GetOrdersByKitchen", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetOrders(ctx context.Context, in *OrdersRequest, opts ...grpc.CallOption) (*OrdersResponse, error) {
	out := new(OrdersResponse)
	err := c.cc.Invoke(ctx, "/proto.order.order.OrderService/GetOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetOrdersByEstablishment(ctx context.Context, in *OrdersRequest, opts ...grpc.CallOption) (*OrdersResponse, error) {
	out := new(OrdersResponse)
	err := c.cc.Invoke(ctx, "/proto.order.order.OrderService/GetOrdersByEstablishment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetOrderByWaiter(ctx context.Context, in *ID, opts ...grpc.CallOption) (*OrdersResponse, error) {
	out := new(OrdersResponse)
	err := c.cc.Invoke(ctx, "/proto.order.order.OrderService/GetOrderByWaiter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetOrderPendingByWaiter(ctx context.Context, in *ID, opts ...grpc.CallOption) (*OrdersResponse, error) {
	out := new(OrdersResponse)
	err := c.cc.Invoke(ctx, "/proto.order.order.OrderService/GetOrderPendingByWaiter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetOrderByID(ctx context.Context, in *GetOrderByIDRequest, opts ...grpc.CallOption) (*OrderResponse, error) {
	out := new(OrderResponse)
	err := c.cc.Invoke(ctx, "/proto.order.order.OrderService/GetOrderByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) AddProductsToOrder(ctx context.Context, in *AddProductsToOrderRequest, opts ...grpc.CallOption) (*AddProductsToOrderResponse, error) {
	out := new(AddProductsToOrderResponse)
	err := c.cc.Invoke(ctx, "/proto.order.order.OrderService/AddProductsToOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
// All implementations must embed UnimplementedOrderServiceServer
// for forward compatibility
type OrderServiceServer interface {
	CreateLocalOrder(context.Context, *Order) (*CreateResponse, error)
	CreateDeliveryOrder(context.Context, *Order) (*CreateResponse, error)
	GetOrdersByUser(context.Context, *OrdersByUserRequest) (*OrdersResponse, error)
	GetOrdersByKitchen(context.Context, *RequestKitchen) (*OrderProductsResponse, error)
	GetOrders(context.Context, *OrdersRequest) (*OrdersResponse, error)
	GetOrdersByEstablishment(context.Context, *OrdersRequest) (*OrdersResponse, error)
	GetOrderByWaiter(context.Context, *ID) (*OrdersResponse, error)
	GetOrderPendingByWaiter(context.Context, *ID) (*OrdersResponse, error)
	GetOrderByID(context.Context, *GetOrderByIDRequest) (*OrderResponse, error)
	AddProductsToOrder(context.Context, *AddProductsToOrderRequest) (*AddProductsToOrderResponse, error)
	mustEmbedUnimplementedOrderServiceServer()
}

// UnimplementedOrderServiceServer must be embedded to have forward compatible implementations.
type UnimplementedOrderServiceServer struct {
}

func (UnimplementedOrderServiceServer) CreateLocalOrder(context.Context, *Order) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLocalOrder not implemented")
}
func (UnimplementedOrderServiceServer) CreateDeliveryOrder(context.Context, *Order) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDeliveryOrder not implemented")
}
func (UnimplementedOrderServiceServer) GetOrdersByUser(context.Context, *OrdersByUserRequest) (*OrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrdersByUser not implemented")
}
func (UnimplementedOrderServiceServer) GetOrdersByKitchen(context.Context, *RequestKitchen) (*OrderProductsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrdersByKitchen not implemented")
}
func (UnimplementedOrderServiceServer) GetOrders(context.Context, *OrdersRequest) (*OrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrders not implemented")
}
func (UnimplementedOrderServiceServer) GetOrdersByEstablishment(context.Context, *OrdersRequest) (*OrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrdersByEstablishment not implemented")
}
func (UnimplementedOrderServiceServer) GetOrderByWaiter(context.Context, *ID) (*OrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderByWaiter not implemented")
}
func (UnimplementedOrderServiceServer) GetOrderPendingByWaiter(context.Context, *ID) (*OrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderPendingByWaiter not implemented")
}
func (UnimplementedOrderServiceServer) GetOrderByID(context.Context, *GetOrderByIDRequest) (*OrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderByID not implemented")
}
func (UnimplementedOrderServiceServer) AddProductsToOrder(context.Context, *AddProductsToOrderRequest) (*AddProductsToOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProductsToOrder not implemented")
}
func (UnimplementedOrderServiceServer) mustEmbedUnimplementedOrderServiceServer() {}

// UnsafeOrderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderServiceServer will
// result in compilation errors.
type UnsafeOrderServiceServer interface {
	mustEmbedUnimplementedOrderServiceServer()
}

func RegisterOrderServiceServer(s grpc.ServiceRegistrar, srv OrderServiceServer) {
	s.RegisterService(&OrderService_ServiceDesc, srv)
}

func _OrderService_CreateLocalOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Order)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CreateLocalOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.order.order.OrderService/CreateLocalOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CreateLocalOrder(ctx, req.(*Order))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_CreateDeliveryOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Order)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CreateDeliveryOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.order.order.OrderService/CreateDeliveryOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CreateDeliveryOrder(ctx, req.(*Order))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetOrdersByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrdersByUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetOrdersByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.order.order.OrderService/GetOrdersByUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetOrdersByUser(ctx, req.(*OrdersByUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetOrdersByKitchen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestKitchen)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetOrdersByKitchen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.order.order.OrderService/GetOrdersByKitchen",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetOrdersByKitchen(ctx, req.(*RequestKitchen))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.order.order.OrderService/GetOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetOrders(ctx, req.(*OrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetOrdersByEstablishment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetOrdersByEstablishment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.order.order.OrderService/GetOrdersByEstablishment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetOrdersByEstablishment(ctx, req.(*OrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetOrderByWaiter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetOrderByWaiter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.order.order.OrderService/GetOrderByWaiter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetOrderByWaiter(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetOrderPendingByWaiter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetOrderPendingByWaiter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.order.order.OrderService/GetOrderPendingByWaiter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetOrderPendingByWaiter(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetOrderByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetOrderByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.order.order.OrderService/GetOrderByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetOrderByID(ctx, req.(*GetOrderByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_AddProductsToOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProductsToOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).AddProductsToOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.order.order.OrderService/AddProductsToOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).AddProductsToOrder(ctx, req.(*AddProductsToOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderService_ServiceDesc is the grpc.ServiceDesc for OrderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.order.order.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLocalOrder",
			Handler:    _OrderService_CreateLocalOrder_Handler,
		},
		{
			MethodName: "CreateDeliveryOrder",
			Handler:    _OrderService_CreateDeliveryOrder_Handler,
		},
		{
			MethodName: "GetOrdersByUser",
			Handler:    _OrderService_GetOrdersByUser_Handler,
		},
		{
			MethodName: "GetOrdersByKitchen",
			Handler:    _OrderService_GetOrdersByKitchen_Handler,
		},
		{
			MethodName: "GetOrders",
			Handler:    _OrderService_GetOrders_Handler,
		},
		{
			MethodName: "GetOrdersByEstablishment",
			Handler:    _OrderService_GetOrdersByEstablishment_Handler,
		},
		{
			MethodName: "GetOrderByWaiter",
			Handler:    _OrderService_GetOrderByWaiter_Handler,
		},
		{
			MethodName: "GetOrderPendingByWaiter",
			Handler:    _OrderService_GetOrderPendingByWaiter_Handler,
		},
		{
			MethodName: "GetOrderByID",
			Handler:    _OrderService_GetOrderByID_Handler,
		},
		{
			MethodName: "AddProductsToOrder",
			Handler:    _OrderService_AddProductsToOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order/order.proto",
}

// OrderStatusServiceClient is the client API for OrderStatusService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderStatusServiceClient interface {
	PayLocal(ctx context.Context, in *PayLocalRequest, opts ...grpc.CallOption) (*PayLocalResponse, error)
	PayDelivery(ctx context.Context, in *PayDeliveryRequest, opts ...grpc.CallOption) (*PayDeliveryResponse, error)
	CompleteProduct(ctx context.Context, in *CompleteProductRequest, opts ...grpc.CallOption) (*CompleteProductResponse, error)
	CapturePayment(ctx context.Context, in *CapturePaymentRequest, opts ...grpc.CallOption) (*CapturePaymentResponse, error)
	DeliverProducts(ctx context.Context, in *DeliverProductRequest, opts ...grpc.CallOption) (*DeliverProductResponse, error)
}

type orderStatusServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderStatusServiceClient(cc grpc.ClientConnInterface) OrderStatusServiceClient {
	return &orderStatusServiceClient{cc}
}

func (c *orderStatusServiceClient) PayLocal(ctx context.Context, in *PayLocalRequest, opts ...grpc.CallOption) (*PayLocalResponse, error) {
	out := new(PayLocalResponse)
	err := c.cc.Invoke(ctx, "/proto.order.order.OrderStatusService/PayLocal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderStatusServiceClient) PayDelivery(ctx context.Context, in *PayDeliveryRequest, opts ...grpc.CallOption) (*PayDeliveryResponse, error) {
	out := new(PayDeliveryResponse)
	err := c.cc.Invoke(ctx, "/proto.order.order.OrderStatusService/PayDelivery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderStatusServiceClient) CompleteProduct(ctx context.Context, in *CompleteProductRequest, opts ...grpc.CallOption) (*CompleteProductResponse, error) {
	out := new(CompleteProductResponse)
	err := c.cc.Invoke(ctx, "/proto.order.order.OrderStatusService/CompleteProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderStatusServiceClient) CapturePayment(ctx context.Context, in *CapturePaymentRequest, opts ...grpc.CallOption) (*CapturePaymentResponse, error) {
	out := new(CapturePaymentResponse)
	err := c.cc.Invoke(ctx, "/proto.order.order.OrderStatusService/CapturePayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderStatusServiceClient) DeliverProducts(ctx context.Context, in *DeliverProductRequest, opts ...grpc.CallOption) (*DeliverProductResponse, error) {
	out := new(DeliverProductResponse)
	err := c.cc.Invoke(ctx, "/proto.order.order.OrderStatusService/DeliverProducts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderStatusServiceServer is the server API for OrderStatusService service.
// All implementations must embed UnimplementedOrderStatusServiceServer
// for forward compatibility
type OrderStatusServiceServer interface {
	PayLocal(context.Context, *PayLocalRequest) (*PayLocalResponse, error)
	PayDelivery(context.Context, *PayDeliveryRequest) (*PayDeliveryResponse, error)
	CompleteProduct(context.Context, *CompleteProductRequest) (*CompleteProductResponse, error)
	CapturePayment(context.Context, *CapturePaymentRequest) (*CapturePaymentResponse, error)
	DeliverProducts(context.Context, *DeliverProductRequest) (*DeliverProductResponse, error)
	mustEmbedUnimplementedOrderStatusServiceServer()
}

// UnimplementedOrderStatusServiceServer must be embedded to have forward compatible implementations.
type UnimplementedOrderStatusServiceServer struct {
}

func (UnimplementedOrderStatusServiceServer) PayLocal(context.Context, *PayLocalRequest) (*PayLocalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PayLocal not implemented")
}
func (UnimplementedOrderStatusServiceServer) PayDelivery(context.Context, *PayDeliveryRequest) (*PayDeliveryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PayDelivery not implemented")
}
func (UnimplementedOrderStatusServiceServer) CompleteProduct(context.Context, *CompleteProductRequest) (*CompleteProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteProduct not implemented")
}
func (UnimplementedOrderStatusServiceServer) CapturePayment(context.Context, *CapturePaymentRequest) (*CapturePaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CapturePayment not implemented")
}
func (UnimplementedOrderStatusServiceServer) DeliverProducts(context.Context, *DeliverProductRequest) (*DeliverProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeliverProducts not implemented")
}
func (UnimplementedOrderStatusServiceServer) mustEmbedUnimplementedOrderStatusServiceServer() {}

// UnsafeOrderStatusServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderStatusServiceServer will
// result in compilation errors.
type UnsafeOrderStatusServiceServer interface {
	mustEmbedUnimplementedOrderStatusServiceServer()
}

func RegisterOrderStatusServiceServer(s grpc.ServiceRegistrar, srv OrderStatusServiceServer) {
	s.RegisterService(&OrderStatusService_ServiceDesc, srv)
}

func _OrderStatusService_PayLocal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayLocalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderStatusServiceServer).PayLocal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.order.order.OrderStatusService/PayLocal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderStatusServiceServer).PayLocal(ctx, req.(*PayLocalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderStatusService_PayDelivery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayDeliveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderStatusServiceServer).PayDelivery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.order.order.OrderStatusService/PayDelivery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderStatusServiceServer).PayDelivery(ctx, req.(*PayDeliveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderStatusService_CompleteProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderStatusServiceServer).CompleteProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.order.order.OrderStatusService/CompleteProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderStatusServiceServer).CompleteProduct(ctx, req.(*CompleteProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderStatusService_CapturePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CapturePaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderStatusServiceServer).CapturePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.order.order.OrderStatusService/CapturePayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderStatusServiceServer).CapturePayment(ctx, req.(*CapturePaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderStatusService_DeliverProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliverProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderStatusServiceServer).DeliverProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.order.order.OrderStatusService/DeliverProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderStatusServiceServer).DeliverProducts(ctx, req.(*DeliverProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderStatusService_ServiceDesc is the grpc.ServiceDesc for OrderStatusService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderStatusService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.order.order.OrderStatusService",
	HandlerType: (*OrderStatusServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PayLocal",
			Handler:    _OrderStatusService_PayLocal_Handler,
		},
		{
			MethodName: "PayDelivery",
			Handler:    _OrderStatusService_PayDelivery_Handler,
		},
		{
			MethodName: "CompleteProduct",
			Handler:    _OrderStatusService_CompleteProduct_Handler,
		},
		{
			MethodName: "CapturePayment",
			Handler:    _OrderStatusService_CapturePayment_Handler,
		},
		{
			MethodName: "DeliverProducts",
			Handler:    _OrderStatusService_DeliverProducts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order/order.proto",
}
