// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: classification/classification.proto

package classification

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ClassImgServiceClient is the client API for ClassImgService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClassImgServiceClient interface {
	ClassImg(ctx context.Context, in *RequestClassImg, opts ...grpc.CallOption) (*ResponseClassImg, error)
}

type classImgServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClassImgServiceClient(cc grpc.ClientConnInterface) ClassImgServiceClient {
	return &classImgServiceClient{cc}
}

func (c *classImgServiceClient) ClassImg(ctx context.Context, in *RequestClassImg, opts ...grpc.CallOption) (*ResponseClassImg, error) {
	out := new(ResponseClassImg)
	err := c.cc.Invoke(ctx, "/ClassImgService/ClassImg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClassImgServiceServer is the server API for ClassImgService service.
// All implementations must embed UnimplementedClassImgServiceServer
// for forward compatibility
type ClassImgServiceServer interface {
	ClassImg(context.Context, *RequestClassImg) (*ResponseClassImg, error)
	mustEmbedUnimplementedClassImgServiceServer()
}

// UnimplementedClassImgServiceServer must be embedded to have forward compatible implementations.
type UnimplementedClassImgServiceServer struct {
}

func (UnimplementedClassImgServiceServer) ClassImg(context.Context, *RequestClassImg) (*ResponseClassImg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClassImg not implemented")
}
func (UnimplementedClassImgServiceServer) mustEmbedUnimplementedClassImgServiceServer() {}

// UnsafeClassImgServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClassImgServiceServer will
// result in compilation errors.
type UnsafeClassImgServiceServer interface {
	mustEmbedUnimplementedClassImgServiceServer()
}

func RegisterClassImgServiceServer(s grpc.ServiceRegistrar, srv ClassImgServiceServer) {
	s.RegisterService(&ClassImgService_ServiceDesc, srv)
}

func _ClassImgService_ClassImg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestClassImg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassImgServiceServer).ClassImg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ClassImgService/ClassImg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassImgServiceServer).ClassImg(ctx, req.(*RequestClassImg))
	}
	return interceptor(ctx, in, info, handler)
}

// ClassImgService_ServiceDesc is the grpc.ServiceDesc for ClassImgService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClassImgService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ClassImgService",
	HandlerType: (*ClassImgServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClassImg",
			Handler:    _ClassImgService_ClassImg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "classification/classification.proto",
}
