# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: classification/classification.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#classification/classification.proto\"\x1e\n\x0fRequestClassImg\x12\x0b\n\x03img\x18\x01 \x01(\x0c\"\x1e\n\x10ResponseClassImg\x12\n\n\x02id\x18\x01 \x01(\r2@\n\rValidateOrder\x12/\n\x08\x43lassImg\x12\x10.RequestClassImg\x1a\x11.ResponseClassImgB\x11Z\x0f\x63lassification/b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'classification.classification_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\017classification/'
  _REQUESTCLASSIMG._serialized_start=39
  _REQUESTCLASSIMG._serialized_end=69
  _RESPONSECLASSIMG._serialized_start=71
  _RESPONSECLASSIMG._serialized_end=101
  _VALIDATEORDER._serialized_start=103
  _VALIDATEORDER._serialized_end=167
# @@protoc_insertion_point(module_scope)
